import { test } from 'node:test';
import assert from 'node:assert/strict';
import { generateApp } from '../src/model/codegen';
import { PALETTE_CATEGORIES, paletteItems } from '../src/model/components';
import { ImportError, importApp } from '../src/model/fromR';
import { parseR } from '../src/model/rparse';
import { emptyProject, starterProject } from '../src/model/templates';
import { createNode, findNode, insertNode, walk } from '../src/model/tree';
import type { UINode } from '../src/model/types';
import { validate } from '../src/model/validate';
import { initialState, reducer } from '../src/state/store';

const main = (root: UINode) => root.children.find((c) => c.type === 'main')!;
const sidebar = (root: UINode) => root.children.find((c) => c.type === 'sidebar')!;

/** Tree without internal ids, for structural comparison. */
function shape(n: UINode): unknown {
  return { type: n.type, props: n.props, raw: n.raw, extra: n.extra, children: n.children.map(shape) };
}

function roundTrip(root: UINode) {
  const code = generateApp(root).app;
  const back = importApp(code).root;
  assert.equal(generateApp(back).app, code, 'code -> design -> code is stable');
  return back;
}

test('the starter project survives a round trip unchanged', () => {
  const root = starterProject().root;
  const back = roundTrip(root);
  assert.deepEqual(shape(back), shape(root));
});

test('every palette component survives a round trip', () => {
  let root = emptyProject().root;
  const cols = createNode('layout_columns', root);
  root = insertNode(root, main(root).id, 0, cols);
  for (const cat of PALETTE_CATEGORIES) {
    for (const def of paletteItems(cat)) {
      if (def.type === 'nav_panel') continue; // comes with the tabset
      const parent = def.io === 'input' ? sidebar(root).id : cols.id;
      root = insertNode(root, parent, 999, createNode(def.type, root));
    }
  }
  const back = roundTrip(root);
  assert.deepEqual(shape(back), shape(root));
});

test('non-default values, raw expressions and other arguments round-trip', () => {
  const code = `library(shiny)
library(bslib)

ui <- page_sidebar(
  title = "Cars",
  sidebar = sidebar(
    width = 300,
    position = "right",
    selectInput("xvar", "X variable", choices = names(mtcars), selected = "mpg"),
    sliderInput("n", "Rows", 1, 32, 10, animate = TRUE)
  ),
  theme = bs_theme(preset = "shiny"),
  layout_columns(
    col_widths = c(4, 8),
    value_box("Cars", nrow(mtcars), theme = "info"),
    card(card_header("Plot"), plotOutput("scatter", height = "300px"))
  )
)

server <- function(input, output, session) {
  output$scatter <- renderPlot(plot(mtcars[[input$xvar]]))
}

shinyApp(ui, server)
`;
  const root = importApp(code).root;
  assert.equal(root.props.title, 'Cars');
  assert.equal(root.raw?.theme, 'bs_theme(preset = "shiny")');
  const sb = sidebar(root);
  assert.equal(sb.props.width, 300);
  assert.equal(sb.props.position, 'right');
  const [select, slider] = sb.children;
  assert.equal(select.type, 'selectInput');
  assert.equal(select.raw?.choices, 'names(mtcars)');
  assert.equal(select.props.selected, 'mpg');
  assert.equal(slider.props.max, 32);
  assert.equal(slider.extra, 'animate = TRUE');
  const cols = main(root).children[0];
  assert.equal(cols.props.col_widths, '4, 8');
  const [vb, card] = cols.children;
  assert.equal(vb.type, 'value_box');
  assert.equal(vb.raw?.value, 'nrow(mtcars)');
  assert.equal(card.props.header, 'Plot');
  assert.equal(card.children[0].props.height, '300px');
  assert.equal(card.children[0].props.code, 'plot(mtcars[[input$xvar]])');
  assert.equal(root.props.serverCode, '');

  const regenerated = generateApp(root).app;
  for (const piece of [
    'choices = names(mtcars)',
    'animate = TRUE',
    'theme = bs_theme(preset = "shiny")',
    'value = nrow(mtcars)',
    'position = "right"',
    'width = 300',
  ])
    assert.ok(regenerated.includes(piece), `missing ${piece}`);
  assert.equal(generateApp(importApp(regenerated).root).app, regenerated);
});

test('unknown UI becomes R code blocks, extra code is kept', () => {
  const code = `# Generated by TruthEditor
library(shiny)
library(bslib)
library(DT)

# Prepare the data once
cars <- mtcars |>
  transform(kpl = mpg * 0.425)

ui <- page_fillable(
  title = "Mileage",
  navset_card_tab(
    nav_panel("Table", DT::DTOutput("tbl")),
    nav_panel("About", markdown("**Hello**"), p("Plain text")),
    nav_spacer()
  ),
  div(class = "footer", "(c) 2026")
)

server <- function(input, output, session) {
  # Inputs: none

  filtered <- reactive({
    cars[cars$kpl > 5, ]
  })

  output$tbl <- DT::renderDT(filtered())
}

shinyApp(ui = ui, server = server)
`;
  const root = importApp(code).root;
  assert.equal(root.props.layout, 'page_fillable');
  assert.equal(root.props.setup, 'library(DT)\n\n# Prepare the data once\ncars <- mtcars |>\n  transform(kpl = mpg * 0.425)');
  assert.equal(
    root.props.serverCode,
    'filtered <- reactive({\n  cars[cars$kpl > 5, ]\n})\n\noutput$tbl <- DT::renderDT(filtered())',
  );
  const [tabs, footer] = main(root).children;
  assert.equal(tabs.type, 'navset_card_tab');
  assert.deepEqual(
    tabs.children.map((c) => c.type),
    ['nav_panel', 'nav_panel', 'rcode'],
  );
  assert.equal(tabs.children[0].children[0].type, 'rcode');
  assert.equal(tabs.children[0].children[0].props.code, 'DT::DTOutput("tbl")');
  assert.deepEqual(
    tabs.children[1].children.map((c) => c.type),
    ['rcode', 'paragraph'],
  );
  // div() is a cell: its attributes become other arguments, the text an R code block inside it
  assert.equal(footer.type, 'cell');
  assert.equal(footer.extra, 'class = "footer"');
  assert.equal(footer.children[0].type, 'rcode');
  assert.equal(footer.children[0].props.code, '"(c) 2026"');
  assert.match(generateApp(root).app, /div\(class = "footer", "\(c\) 2026"\)/);

  const regenerated = generateApp(root).app;
  assert.equal(generateApp(importApp(regenerated).root).app, regenerated);
  parseR(regenerated);
  assert.deepEqual(validate(root).filter((i) => i.severity === 'error'), []);
});

test('server code is matched to its component by id and render function', () => {
  const code = `ui <- page_fluid(
  actionButton("go", "Go", class = "btn-success"),
  textOutput("msg"),
  plotOutput("p")
)
server <- function(input, output, session) {
  observeEvent(input$go, {
    showNotification("Clicked")
  })
  output$msg <- renderText({ "hi" })
  output$p <- renderCachedPlot(plot(1), cacheKeyExpr = 1)
}
shinyApp(ui, server)`;
  const root = importApp(code).root;
  const [btn, msg, plot] = main(root).children;
  assert.equal(btn.props.class, 'btn-success');
  assert.equal(btn.props.code, 'showNotification("Clicked")');
  assert.equal(msg.props.code, '"hi"');
  assert.equal(plot.props.code, ''); // renderCachedPlot is not renderPlot: kept as other server code
  assert.equal(root.props.serverCode, 'output$p <- renderCachedPlot(plot(1), cacheKeyExpr = 1)');
  const app = generateApp(root).app;
  assert.equal((app.match(/output\$p/g) ?? []).length, 1, 'no duplicate render for p');
  assert.deepEqual(validate(root).filter((i) => i.severity !== 'error' && i.message.includes('no server code')), []);
});

test('syntax errors report line and column', () => {
  assert.throws(
    () => importApp('ui <- page_fluid(\n  textOutput("a"\n)\nserver <- function(input, output) {}'),
    (e: unknown) => e instanceof ImportError && e.line === 4 && /expected ',' or '\)' in the call to page_fluid\(\)/.test(e.message),
  );
  assert.throws(() => importApp('ui <- fluidPage()\nserver <- function(input, output) {}'), /page_sidebar\(\), page_fillable\(\) or page_fluid\(\)/);
  assert.throws(() => importApp('x <- 1'), /needs a `ui <-/);
});

test('editing code updates the design, keeps ids, and visual edits regenerate the code', () => {
  let s = initialState(starterProject());
  const plotId = (() => {
    let id = '';
    walk(s.root, (n) => {
      if (n.type === 'plotOutput') id = n.id;
    });
    return id;
  })();
  s = reducer(s, { type: 'select', id: plotId });
  const code = generateApp(s.root).app.replace('"Number of bins:"', '"Bins"');
  s = reducer(s, { type: 'setCode', code });
  assert.equal(s.codeDraft, code);
  assert.equal(s.codeError, null);
  assert.equal(sidebar(s.root).children[0].props.label, 'Bins');
  assert.equal(s.selectedId, plotId, 'selection survives');
  assert.ok(findNode(s.root, plotId));

  // Broken code: design stays, error is reported
  const before = s.root;
  s = reducer(s, { type: 'setCode', code: code.replace('min = 1,', 'min = 1,,,)') });
  assert.equal(s.root, before);
  assert.ok(s.codeError && s.codeError.line > 0);

  // Fix it again, then edit visually: the draft is dropped and code regenerates
  s = reducer(s, { type: 'setCode', code });
  assert.equal(s.codeError, null);
  s = reducer(s, { type: 'updateProps', id: sidebar(s.root).children[0].id, patch: { label: 'Number of bins' } });
  assert.equal(s.codeDraft, null);

  // Typing several characters is a single undo step
  let t = initialState(starterProject());
  const base = generateApp(t.root).app;
  for (const title of ['A', 'AB', 'ABC']) t = reducer(t, { type: 'setCode', code: base.replace('Old Faithful Geyser Data', title) });
  assert.equal(t.past.length, 1);
  assert.equal(t.root.props.title, 'ABC');
});

test('files and app.R from before the rename to DropToApp still open', async () => {
  const { isProject, starterProject } = await import('../src/model/templates');
  const legacy = { ...starterProject(), format: 'truth-editor/v1' };
  assert.equal(isProject(legacy), true, 'old .shinydesign.json files');
  assert.equal(isProject(starterProject()), true);
  assert.equal(starterProject().format, 'droptoapp/v1');
  const code = generateApp(starterProject().root).app;
  assert.match(code, /^# Generated by DropToApp\n/);
  const old = code.replace('# Generated by DropToApp', '# Generated by TruthEditor');
  assert.equal(importApp(old).root.props.setup, '', 'the old header is not kept as setup code');
});
