import { COMPONENTS, nodeToR, serverCode } from './components';
import { indent, named, rCall, rStr } from './rcode';
import { walk } from './tree';
import type { UINode } from './types';

export interface GeneratedCode {
  ui: string;
  server: string;
  app: string;
}

export const HEADER_COMMENT = '# Generated by TruthEditor';
export const INPUTS_COMMENT_PREFIX = '# Inputs:';

export function nodeExpr(node: UINode): string {
  return nodeToR(node, node.children.map(nodeExpr));
}

function region(root: UINode, type: 'sidebar' | 'main'): UINode | undefined {
  return root.children.find((c) => c.type === type);
}

function themeArg(root: UINode): string | undefined {
  if (root.raw?.theme) return `theme = ${root.raw.theme}`;
  const theme = String(root.props.theme ?? 'default');
  return theme && theme !== 'default' ? `theme = bs_theme(bootswatch = ${rStr(theme)})` : undefined;
}

export function generateUI(root: UINode): string {
  const layout = String(root.props.layout ?? 'page_sidebar');
  const title = String(root.props.title ?? '');
  const main = region(root, 'main')?.children.map(nodeExpr) ?? [];
  const args: (string | undefined)[] = [
    root.raw?.title ? `title = ${root.raw.title}` : named('title', title ? rStr(title) : undefined),
  ];
  if (layout === 'page_sidebar') {
    const sb = region(root, 'sidebar');
    if (root.raw?.sidebar) args.push(`sidebar = ${root.raw.sidebar}`);
    else if (sb) args.push(`sidebar = ${nodeExpr(sb)}`);
  }
  args.push(themeArg(root), root.extra?.trim().replace(/,\s*$/, '') || undefined, ...main);
  return `ui <- ${rCall(layout, args)}`;
}

export function generateServer(root: UINode): string {
  const blocks: string[] = [];
  const inputs: string[] = [];
  const layout = String(root.props.layout ?? 'page_sidebar');
  // The sidebar's contents only exist in the app when the layout has a sidebar.
  const regions = root.children.filter((r) => r.type === 'main' || layout === 'page_sidebar');
  for (const r of regions) {
    walk(r, (n) => {
      const def = COMPONENTS[n.type];
      if (def.io === 'input' && n.type !== 'actionButton') inputs.push(`input$${n.props.id}`);
      const code = serverCode(n);
      if (code) blocks.push(code);
    });
  }
  const sections: string[] = [];
  if (inputs.length) sections.push(`${INPUTS_COMMENT_PREFIX} ${inputs.join(', ')}`);
  const extra = String(root.props.serverCode ?? '').trim();
  if (extra) sections.push(extra);
  if (blocks.length) sections.push(blocks.join('\n\n'));
  const body = sections.length ? indent(sections.join('\n\n')) : '';
  return `server <- function(input, output, session) {\n${body}${body ? '\n' : ''}}`;
}

export function generateApp(root: UINode): GeneratedCode {
  const ui = generateUI(root);
  const server = generateServer(root);
  const setup = String(root.props.setup ?? '').trim();
  const app = [HEADER_COMMENT, 'library(shiny)', 'library(bslib)', '', ...(setup ? [setup, ''] : []), ui, '', server, '', 'shinyApp(ui, server)', ''].join(
    '\n',
  );
  return { ui, server, app };
}
